# Generated by Django 6.0.7 on 2026-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('thumb', models.FloatField(default=0)),
                ('index', models.FloatField(default=0)),
                ('middle', models.FloatField(default=0)),
                ('ring', models.FloatField(default=0)),
                ('little', models.FloatField(default=0)),
                ('recommended_size', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
